image: python:3.6

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  script:
  - python -m doctest ./task1/game.py
  - python -m doctest ./task2/game.py
  - python -m doctest ./task2/gameparser.py